spring:
  datasource:
    url: mysql://b1818825d70276:3fce1a72@eu-cdbr-west-03.cleardb.net/heroku_cfe4786bdfd69b0?reconnect=true
    username: b1818825d70276
    password: 3fce1a72

#    mysql://b1818825d70276:3fce1a72@eu-cdbr-west-03.cleardb.net/heroku_cfe4786bdfd69b0?reconnect=true
#spring:
#  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}